function [methodinfo,structs,enuminfo]=psproto;
%PSPROTO Create structures to define interfaces found in 'psmatlab'.

%This function was generated by loadlibrary.m parser version 1.1.6.13 on Tue Feb 21 10:44:58 2006
%perl options:'psmatlab.i -outfile=psproto.m'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival);
structs=[];enuminfo=[];fcnNum=1;
% extern " C " char * psjavascript ( char * scripttext ); 
fcns.name{fcnNum}='psjavascript'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='cstring'; fcns.RHS{fcnNum}={'cstring'};fcnNum=fcnNum+1;
% extern " C " unsigned int psjavascriptu ( unsigned short * scripttext ); 
fcns.name{fcnNum}='psjavascriptu'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='uint32'; fcns.RHS{fcnNum}={'uint16Ptr'};fcnNum=fcnNum+1;
% extern " C " void psjavascriptgetresult ( unsigned short * result ); 
fcns.name{fcnNum}='psjavascriptgetresult'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'uint16Ptr'};fcnNum=fcnNum+1;
% extern " C " void pslaunch ( void ); 
fcns.name{fcnNum}='pslaunch'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
% extern " C " void psquit ( void ); 
fcns.name{fcnNum}='psquit'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
methodinfo=fcns;